package com.ulsa.oaxaca.edu.proyecto_banco.utils;

public enum TipoTransaccion {
    CREACION_SUCURSAL,
    ELIMINCION_SUCURSAL,
    CREACION_PERSONAL,
    ELIMINACION_PERSONAL,
    CREACION_CUENTA,
    ELIMINACION_CUENTA,
    CREACION_CLIENTE,
    ELIMINACION_CLIENTE,
    TRANSFERENCIA,
    DEPOSITO,
    RETIRO,
    ACTUALIZACION_SUCURSAL,
    ACTUALIZACION_PERSONAL,
    ACTUALIZACION_CUENTA,
    ACTUALIZACION_CLIENTE,
    PAGO_CUENTA,
}